# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd3281582842a68a2b2de2d338dcabb58f3e8fc285933a009d374bbf8634b4a07874c26d78eb14b5080c952731f125921867cd18c73f9a27be01d6e455f65734

test:
  secret_key_base: e7c2add4c7d8fee46dad05258a53df38c3eb42744fde7362835d46d4b150e34376299ca8e4e274017fc57329385e4a1243bad5ba3bb95c72f74e763bbfd3d4ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
